### ISSUE TITLE
Text scrolls like in Star Wars from bottom to top instead of flashing on a single line.

### ISSUE THREAD

**Issue by egalion** [pasky/speedread#13]
Hello,

I use Fedora 18 (tried it both with xterm and lilyterm). Instead of flashing the text on a single line like in your demo, the text scrolls from the bottom to the top. I tried it in Ubuntu 12.04 and it worked OK.

Is there a way to fix this?

**Comment by sesas** [comment]
Case closed! 👍

**Comment by pasky** [comment]
Thanks for providing the support :)
