### ISSUE TITLE
Please tag a commit

### ISSUE THREAD

**Issue by hashier** [pasky/speedread#17]
I created a Formula for home-brew but home-brew maintainers want to have a tagged commit to point to for the download. Therefore I would really like to see a tag so the Formula can be pushed upstream.

**Comment by pasky** [comment]
No problem - I just tagged v1.0.

I also merged some outstanding though quite non-trivial pull requests. If someone tests them and gives positive feedback, I can tag this as v1.1 in a short time.

**Comment by hashier** [comment]
Cool, Thanks!

**Comment by hashier** [comment]
https://github.com/Homebrew/homebrew/pull/47935

It's done
