### ISSUE TITLE
-w: command not found?

### ISSUE THREAD

**Issue by liamcoded** [pasky/speedread#20]
I tried your example with my file and it hasn't worked. Could you tell me what am I doing wrong?

I add the following 
`cat README.txt | -w 250`

and get this in bash and zsh
`-w: command not found`

**Comment by nguyeho7** [comment]
You don't run the script itself. -w is just a parameter, you need to include ./speedread as well, as in the example.

**Comment by liamcoded** [comment]
I am sorry, I still don't get it. I am new to terminal. And I hoped I could use your program to practice reading faster while also learning about the Terminal. Could you give me the example of what I would write in terminal if I wanted to read a .txt file from my desktop?

**Comment by pasky** [comment]
I'm confused, what goes wrong if you just follow the first example in README, ``cat tea.txt | ./speedread -w 250``?
