### ISSUE TITLE
Errors are printed while using the program

### ISSUE THREAD

**Issue by Wysaard** [pasky/speedread#22]
Now and then the program will print errors.

For example:

> Use of the encoding pragma is deprecated at speedread-original/speedread line 39.

and

> 99918 wpmBytes implicitly upgraded into wide characters as iso-8859-1 at speedread-original/speedread line 194.

This is fixed by some minimal changes as proposed in this pull-request: #21

**Comment by pasky** [comment]
Merged PR #21
