### ISSUE TITLE
Speedreading from a file with special characters does not work

### ISSUE THREAD

**Issue by vanniktech** [pasky/speedread#25]
```sh
echo "Möööööööööö" > t
speedread t
```

will yield:

```sh
MÃ¶Ã¶Ã¶Ã¶Ã¶Ã¶Ã¶Ã¶Ã¶Ã¶
```

<img width="570" alt="screen shot 2018-05-01 at 16 56 24" src="https://user-images.githubusercontent.com/5759366/39477774-983a221e-4d60-11e8-8fee-fec8ff4bd337.png">

```sh
echo "Möööööööööö" | speedread
```

does work though.

<img width="570" alt="screen shot 2018-05-01 at 16 57 02" src="https://user-images.githubusercontent.com/5759366/39477805-af5a44a6-4d60-11e8-87e5-b2cf7179f33f.png">

**Comment by mipper** [comment]
Workaround for this is to cat the file and pipe it into speedread.

`cat r | speedread`
