### ISSUE TITLE
speedread + espeak

### ISSUE THREAD

**Issue by OrionRandD** [pasky/speedread#27]
I am trying to figure out how to use
speedread with espeak. I think I have to 

cat book.txt | ./speedread -w 230 | espeak

Works, but I cannot see the text words going by. I can 
only hear espeak - speaking the book

**Comment by vegan19** [comment]
Hello. Did you find out?

**Comment by OrionRandD** [comment]
> Hello. Did you find out?

nope. You can close the issue...

**Comment by WuerfelDev** [comment]
this: `cat book.txt | tee >(espeak) | speedread`

But syncing the actual output speeds with each other seems rather impossible (for example large numbers take longer to pronounce and it gets out of sync)

**Comment by vegan19** [comment]
In 225 line on speedread file I add such line ( don't need remove anything, just create blank line and add there)

`system ("espeak -s 200 \"".$current_word."\" 2>&1 >/dev/null &");`

Then I run like that: `speedread -w 200`
 But if someone want, they can play with other numbers.

![1](https://user-images.githubusercontent.com/79129161/145154482-dc4cec99-2807-4212-9047-29db9a0b6568.jpg)
